name: dwmpr
description: A new Flutter project. hello world

dependencies:
  flutter:
    sdk: flutter

  http: ^0.11.3

  font_awesome_flutter: ^7.0.0
  bidirectional_scroll_view: ^0.0.5
  bidirectional_scroll_view: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: RobotoMono
        fonts:
          - asset: assets/RobotoMono-Medium.ttf
